spring:
  datasource:
    username: penta
    password: stagiu
    url: "jdbc:postgresql://localhost:5432/paladiclaudiu012"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update